### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MMK21Hub** [MMK21Hub/MMK21Hub.github.io#3]
- [ ] `easy` Fix mobile support 
- [ ] `easy` Make it installable as a PWA
- [ ] `scary` Fix message chinking
- [ ] `intresting` Use document fragments for loading the chunks
- [ ] `hard` Automate updating the channel JSON files
- [ ] `big` Add obvious missing features, like Search, Jump to Date, etc.
- [ ] `big` Cross-server support??
----
- [ ] Use Material Design somehow
- [ ] Use popper.js for tooltips
- [ ] Use tostify for toasts
----
- [ ] WYSIWYG editor to create channels without having to touch Discord
